title: Ruby developer roadmap
author: Roonyx team
email: it@roonyx.tech
description: >-
  Мы составили карту навыков и компетенций Ruby разработчика, которую можно использовать для развития себя и команды.
  Попробуйте приложить её и к себе!
baseurl: '/ruby-developer'
url: ''
twitter_username: RoonyxTech
github_username: Roonyx
facebook_username: RoonyxTech
linkedin_username: Roonyx
instagram_username: roonyx_tech

# Build settings
theme: minima
exclude: ['README.md', 'LICENSE.md', 'Gemfile.lock', 'Gemfile', '.idea']
plugins:
  - jekyll-feed
